#!/bin/sh

cat <<'EOF'
menuentry 'Windows Boot Manager' --class windows --class os {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root 154F-F40D
    chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
EOF
