[ids]
0001
[global]
oneshot_timeout=1000

[aliases]

esc=leftmouse
8=6
9=7
0=8
-=9
==0
backspace='

y==
u=y
i=u
o=i
p=o
[=p
]=backspace

h=-
j=h
k=j
l=k
;=l
'=;

b=,
n=.
m=b
,=n
.=m

compose=rightmeta

[main]
leftalt=oneshot(alt)
rightalt=oneshot(control)
space=overloadt2(spacefn, space, 200)

capslock=overloadt2(meta, esc, 200)
enter=overloadt2(meta, enter, 200)

leftshift=overloadt2(shift, [, 200)
rightshift=overloadt2(shift, ], 200)



[spacefn]
i=up
k=down
j=left
l=right
s=home
f=end
e=pageup
d=pagedown
backspace=delete
1=f1
2=f2
3=f3
4=f4
5=f5
6=f6
7=f7
8=f8
9=f9
0=f10
'=f11
\=f12

